---
- name: Apache HTTP Server Web Content File(s) Synchronization
  hosts: all
  become: yes

  tasks:
######## /var/www/html/constants.php
    - name: /var/www/html/constants.php
      copy:
        src: _var/www/html/constants.php
        dest: /var/www/html/constants.php
        owner: root
        group: root
        mode: '0644'

    - name: Calculate md5sum /var/www/html/constants.php
      shell: |
          /usr/bin/md5sum /var/www/html/constants.php
      register: md5sum_output

    - name: Display md5sum /var/www/html/constants.php
      debug:
        msg: "{{ md5sum_output.stdout }}"
###############################################################################

###############################################################################
######## End of Content File(s) Synchronization
###############################################################################

